### ISSUE TITLE
`npm i` sometimes fails on AppVeyor CI for node 4

### ISSUE THREAD

**Issue by janpio** [apache/cordova-coho#201]
Two recent cases:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/cordova-coho/build/1.0.487/job/ki3dovjrtuufnib8
https://ci.appveyor.com/project/ApacheSoftwareFoundation/cordova-coho/build/1.0.493/job/b13cs9mn95ws2nta

Between these two was a commit that build successfully with no issues.

**Comment by timbru31** [comment]
Shouldn't this issue be closed because #215 was merged? :)

**Comment by janpio** [comment]
👍
