### ISSUE TITLE
AppVeyor & Travis CI build failures

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-coho#267]
Due to a timeout that affects Node.js 10 on one and Node.js 12 on the other. I don't know if we should increase the Jasmine default timeout, add per-test timeout, or consider some other kind of solution.

Affects 2 PRs that I just raised on the docs: #265 & #266

Previous PR #264 seems to have a green build.

Very strange!

**Comment by breautek** [comment]
Closing as Travis and AppVeyor is not used anymore.
