### ISSUE TITLE
Nightly Build Workflow disabled

### ISSUE THREAD

**Issue by tdemaio** [apache/cordova-coho#291]
# Bug Report

## Problem
Nightly builds are not occurring

### What is expected to happen?
nightly builds are deployed to NPM

### What does actually happen?
Nightly build workflow is not active and no nightly builds are deployed to NPM

## Information

See the note on: https://github.com/apache/cordova-coho/actions/workflows/nightly.yml

See the release history for the cordova-android package here: https://www.npmjs.com/package/cordova-android/v/11.0.0-nightly.**### 2022.6.6.**68a9a318

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Enabled
